### ISSUE TITLE
Question about ast output

### ISSUE THREAD

**Issue by mark8044** [edwardez/bbob_dart#3]
First big thank you to @MartenM and @edwardez for getting this to Null Safety!

I just want to make sure I'm using this correctly before I dive in
Using the sample text: `[u][b][i]Sample Text[/i][/b][/u]` and then running it in bbob as follows:

```
  const validTags = {'url', 'b', 'i', 'u'};

  var ast = parse(
    theString,
     onError: (msg) {
       print(msg);
     },
    openTag: '[',
    closeTag: ']',
    enableEscapeTags: false,
    validTags: validTags,
  );
```

```
  for (var node in ast) {
        debugPrint(node.textContent);
      }
```

I get:

```
flutter: [U]
flutter: [B]
flutter: [I]
flutter: Sample Text
flutter: [/I]
flutter: [/B]
flutter: [/U]
```

I can use this and walk through it and parse it, but it would not consider attributes and nesting might be difficult, so I think I'm going about it incorrectly.   From your example documentation you write:

```
  /// Parsed ast. Note that `b` is parsed as text because
  /// it's not in [validTags].
  ///
  ///[Text{text: 'print'}, Text{text: ' '}, Text{text: '[b]'}, Text{text: 'a'},
  ///Text{text: '[/b]'}, Text{text: ' '},
  ///Element{tag: 'url', attributes: '{https://github.com: https://github.com}',
  ///children: [Text{text: 'hello'}, Text{text: ' '}, Text{text: 'world!'}]},
  ///Text{text: '
  //'}, Text{text: '  '}, Text{text: 'Yes'}, Text{text: ' '},
  // Text{text: 'this's'}, Text{text: ' '}, Text{text: 'an'}, Text{text: ' '},
  // Text{text: 'exampe'}]
```

Is there supposed to be a way to retrieve these attributes and actually walk through this to properly deal with nesting?

And if I use `var theString2='[url="https://www.google.com"]Test[/url]';` then the output is `Test`, none of the URL attribute seem accessible.  

I guess the main question is, how do you walk this tree, the `var ast` appears to be a plain text string?

Thanks for any guidance..!

**Comment by edwardez** [comment]
Hi, please refer to  following section in `README.md`
> I want to render ast into html/markdown...
> You have two ways to render:
>     Similar to https://github.com/JiLiZART/bbob/blob/master/packages/bbob-html/src/index.js, how bbob renders ast into html.
>     Similar to https://github.com/dart-lang/markdown/blob/master/lib/src/html_renderer.dart, bbob_dart has implemented an ast which allows you to walk through the tree using visitor pattern.
> Official support in bbob_dart for a html renderer might not happen in the near future. Feel free to send a pull request if you have a well-tested implementation.

The first was is easier to understand(just a recursive function) but might be harder to maintain/scale. All you need to do is to port the js implemenlation into dart + your customization, my gut is you have to use a lot of `dynamic` as type in your code though.

The second way is my personal preference since it uses proper OO pattern and retains all static types.
see
https://github.com/MartenM/flutter_bbcode/blob/main/lib/flutter_renderer.dart
https://github.com/dasmikko/knocky/blob/master/lib/helpers/bbcodehelper.dart
https://github.com/dart-lang/markdown/blob/master/lib/src/html_renderer.dart
https://github.com/edwardez/BangumiN/blob/40d613d42b3452268368d40c168bc7818a572dd0/app/lib/shared/utils/text/convertor/BBCodeToMarkdown.dart

*You don't need to write from scrach, just copying `html_renderer.dart` + small modification then do a `HtmlRenderer().render(ast)` should be enough*


> Is there supposed to be a way to retrieve these attributes and actually walk through this to properly deal with nesting?
The 
The datastructure is nested since it's a tree(ast - Abstract syntax tree), so you will have to "nest" your call somehow.


> And if I use var theString2='[url="https://www.google.com"]Test[/url]'; then the output is Test, none of the URL attribute seem accessible.



This is what I did:
```dart
  var ast = parse(
    '''[url="https://www.google.com"]Test[/url]''',
    onError: (msg) {
      print(msg);
    },
    openTag: '[',
    closeTag: ']',
    enableEscapeTags: false,
    validTags: validTags,
  );
  ast.forEach(print);
```

and this is the result
`Element{tag: 'url', attributes: '{https://www.google.com: https://www.google.com}', children: [Text{text: 'Test'}]}
`

seems like it's working?

**Comment by mark8044** [comment]
@edwardez Thank you for the detailed explanation.  I think I have yet much to learn.  The AST output is infact working properly for me, but I'm used the result being some kind of iterable list that I could walk, and that is not the case, it seems to just be a string which needs further parsing.

As you mention in the connect of rendering then htmlrenderer seems so easy which is awesome!  

Im actually using the BBCode to build custom widgets which I then put on the screen myself depending on some additional logic so I need to really be able to manipulate the guts of the data.  But thank you for the links, I have much reading ahead of me to figure out how to walk an AST string :)

**Comment by MartenM** [comment]
> Thank you for the detailed explanation. I think I have yet much to learn. The AST output is infact working properly for me, but I'm used the result being some kind of iterable list that I could walk, and that is not the case, it seems to just be a string which needs further parsing.

It's not really a list, but more like a tree structure. If you parse it to AST you should have everything you need to render it properly since you get the elements and the text the element contains. The visitor can be used to 'walk down' this tree in a way you seem to want (more like a list).

You starred my project which I assume you could take a look at. I don't require a second parser, and can do stuff like [quote] en [spoiler] tags pretty well (even nested ones). Might be useful for you too if you need widgets depending on BBCode :)

**Comment by edwardez** [comment]
Closing this bug for now! Let me know if you have any questions
